import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { sanityClient, urlFor } from '../lib/sanity'
import Link from 'next/link'

const recipesQuery = '*[_type == "recipes"]{_id,name,slug,mainlogo}'

export default function Home({recipes}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Samahd Recipe app</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <h1>Welcome to Samahd's Kitchen</h1>

        <div className='row'>
          {recipes?.length > 0 && recipes.map(recipe => (
            <div className="col-md-3">
              <div class="card" style={{"width":"18rem",}}>
              <img class="card-img-top" src={urlFor(recipe.mainlogo).url()} style={{"height": "10rem"}}/>
              <div class="card-body">
                <h5 class="card-title">{recipe.name}</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <Link href="/" class="btn btn-primary">see more</Link>
              </div>
            </div>
          </div>        
          ))}</div>
        
      </div>
    </div>
  )
}

export const getStaticProps = async() =>{
  const recipes = await sanityClient.fetch(recipesQuery)
  return {props: {recipes}}
}